spring:
  profiles:
    active: dev  # 기본 실행은 dev로 (운영에서는 prod로 덮어씌워짐)

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update   # 개발용 기본
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


  flyway:
    enabled: true
    locations: classpath:db/migration  # ✅ SQL 파일 위치
    baseline-on-migrate: true